### ISSUE TITLE
Add gulp tasks to dist to support ionic apps & deploy

### ISSUE THREAD

**Issue by jskrzypek** [mcfly-io/generator-sublime#220]
### todo:
- [x] `ionic:project` task
  - [x] add properties to constants
- [x] `ionic:upload` task

#### `ionic:project`
Need a task to read/create dynamically an `ionic.project` file inside the `distFolder`. The properties written to the file should come from an `ionic` object in [`constants.js`](https://github.com/thaiat/generator-sublime/blob/master/templates/gulps/common/constants.js) (like the testfairy). It should support having different `app_id`s for different targets and dev vs. prod modes (perhaps like the `sentry` task does this?)
It should be JSON in format and have the following contents:
```json
{
  "name": "app-name-to-display-on-ionic-dash",
  "app_id": "<app-id-string-from-apps-ionic-io>"
}
```

#### `ionic:upload`
Need a task to upload the code by running `ionic upload` in the appropriate cordova distfolder (i.e. `dist/<target>/dev` or `dist/<target>/prod`). It needs to have `ionic:project` run first to ensure the content is uploaded to the correct app endpoint on https://apps.ionic.io. We should use the `--note` flag  in the `exec` or `spawn` call to add information about which version of the app we are uploading; this note will appear on the https://apps.ionic.io/apps dashboard. We might also want to allow the user to add a string to this note so they can say what this hotfix is doing. 
The taskFn run should maybe look like this (though how exactly we get the note needs to be figured out
```js
 var taskIonicUpload = function(constants, note, done) {
    if(!helper.isMobile(constants)) {
        return;
    }
    var version = helper.readJsonFile('./package.json').version;
    var noteTag = constants.targetName + '-v' + version + '/' + constants.mode + ': ';
    note = note || yargs.argv.note; // this may need to be something else

    var task = spawn('ionic', ['upload', '--note', noteTag + note], {
        cwd: constants.dist.distFolder
    });
    task.stdout.on('data', function(data) {
        gutil.log(' ' + data);
    });
    task.stderr.on('data', function(data) {
        gutil.log(gutil.colors.red(data));
    });
    task.on('exit', function() {
        done();
    });

};
```

**Comment by jskrzypek** [comment]
Here is a preliminary version of a gulp task to do the `ionic upload ...` calls. You can use `--note` or `-n` to pass the note you want to use. This will be sent to the ionic system with the version number prepended.  Running it like this: 
```sh
gulp ionic:upload --note "Changing color scheme"
```
Is equivalent to the command
```sh
ionic upload --note "v0.0.1: Changing color scheme"
```
The --mode and --target flags still work as normal. We probably want a confirm message as well for production builds, but for now this works, assuming you're careful. 

```js
var taskIonicUpload = function(constants, done) {
    if(!helper.isMobile(constants)) {
        return;
    }
    var note = require('yargs').alias('n', 'note').argv.note;

    var version = helper.readJsonFile('./package.json').version;

    gutil.log('Uploading to apps.ionic.io with the note: "' + gutil.colors.yellow('v' + version + ': ' + note) + '".');
    gutil.log('See this update at '+gutil.colors.blue('https://apps.ionic.io/app/'+ constants.ionic[constants.targetName].app_id +'/deploy')+'.');

    var task = spawn('ionic', ['upload', '--note', '"v' + version + ': ' + note + '"'], {
        cwd: constants.dist.distFolder
    });
    task.stdout.on('data', function(data) {
        gutil.log(' ' + data);
    });
    task.stderr.on('data', function(data) {
        gutil.log(gutil.colors.red(data));
    });
    task.on('exit', function() {
        done();
    });

};
gulp.task('ionic:upload', 'Install the app on android', function(done) {
    var taskname = 'ionic:upload';
    gmux.targets.setClientFolder(constants.clientFolder);
    if(global.options === null) {
        global.options = gmux.targets.askForMultipleTargets(taskname);
        // global.options = gmux.targets.askForSingleTarget(taskname);
    }
    return gmux.createAndRunTasks(gulp, taskIonicUpload, taskname, global.options.target, global.options.mode, constants);
});
```

**Comment by jskrzypek** [comment]
This task is supported by the following `helper.js`
```js
'use strict';

var fs = require('fs');
var gutil = require('gulp-util');
var chalk = require('chalk');
var stripJsonComments = require('strip-json-comments');
var _ = require('lodash');
var path = require('path');
var gmux = require('gulp-mux');
var Q = require('q');
var inquirer = require('inquirer');
var moment = require('moment');

/**
 * Returns true if the target application is mobile
 * It checks the presence of a cordova config file
 * @param  {Object}  constants - The constants
 * @returns {Boolean} - True if the target app is mobile, false otherwise
 */
var isMobile = function(constants) {
    return fs.existsSync('./' + constants.clientFolder + '/config' + constants.targetSuffix + '.xml');
};

/**
 * A generic handler for require('child_process').exec
 * @param  {Object} err - The error object
 * @param  {String} stdout - The stdout string
 * @param  {String} stderr - The stderr string
 * @param  {Object} [opts] - The optional options object
 * @param  {Boolean} [opts.throwOnError=false] - Ask execHandler to throw
 * @param  {Boolean} [opts.stderrIsNotError=false] - Don't treat stderr as error info.
 */
var execHandler = function(err, stdout, stderr, opts) {
    opts = opts || {};
    if(stdout) {
        gutil.log(stdout);
    }
    if(stderr) {
        if(opts.stderrIsNotError) {
            gutil.log(stderr);
        } else {
            gutil.log(chalk.red('Error: ') + stderr);
        }
    }
    if(err) {
        gutil.log(chalk.red('An error occured executing a command line action'));
        if(opts.throwOnErr) {
            throw err;
        }
    }
};

var readTextFile = function(filename) {
    var body = fs.readFileSync(filename, 'utf8');
    return body;
};

var readJsonFile = function(filename) {
    var body = readTextFile(filename);
    return JSON.parse(stripJsonComments(body));
};

var writeTextFile = function(filename, body) {
    fs.writeFileSync(filename, body);
};

var writeJsonFile = function(filename, json) {
    var body = JSON.stringify(json);
    writeTextFile(filename, body);
};

var filterFiles = function(files, extension) {
    return _.filter(files, function(file) {
        return path.extname(file) === extension;
    });
};

var targetToTemplateData = function(target, mode) {
    return {
        targetName: target,
        targetSuffix: gmux.targets.targetToSuffix(target),
        mode: mode
    };
};

var getLatestBuild = function(dest, builds) {
    return _(builds).map(function(build) {
            if(fs.existsSync(dest + '/' + build.path)) {
                build.mtime = fs.statSync(dest + '/' + build.path).mtime;
                build.fullPath = dest + '/' + build.path;
            }
            return build;
        })
        .filter('mtime')
        .sortBy('mtime')
        .last();
};

var findAndroidFile = function(dest) {
    var builds = [{
        path: 'platforms/android/build/outputs/apk/android-armv7-debug.apk'
    }, {
        path: 'platforms/android/build/outputs/apk/android-debug.apk'
    }, {
        path: 'platforms/android/ant-build/MainActivity-debug.apk'
    }];
    return getLatestBuild(dest, builds);
};
var findIOSFile = function(dest, appname) {
    var builds = [{
        path: 'platforms/ios/build/device/' + appname + '.ipa'
    }];
    return getLatestBuild(dest, builds);
};

var checkFileAge = function(file) {
    return Q.Promise(function(resolve, reject) {
        var stats = fs.statSync(file.fullPath);
        var age = moment().diff(stats.mtime);

        if(age && age >= 5 * 60 * 1000) {

            gutil.log(gutil.colors.yellow('Warning: the following file ') + file.path);
            gutil.log(gutil.colors.yellow('was modified more than ') + moment(stats.mtime).fromNow());
            gutil.log(file);
            var questions = [{
                type: 'confirm',
                message: 'Continue deployment anyway?',
                name: 'continue'
            }];
            inquirer.prompt(questions, function(answers) {
                if(answers.continue === false) {
                    reject(new Error('file is old'));
                }
                resolve(null);
            });

        } else {
            resolve(null);
        }
    });
};

module.exports = {
    isMobile: isMobile,
    execHandler: execHandler,
    readTextFile: readTextFile,
    readJsonFile: readJsonFile,
    writeTextFile: writeTextFile,
    writeJsonFile: writeJsonFile,
    filterFiles: filterFiles,
    targetToTemplateData: targetToTemplateData,
    checkFileAge: checkFileAge,
    findAndroidFile: findAndroidFile,
    findIOSFile: findIOSFile
};
```
